# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 日本語行ける？

on:
  push:
    branches: [ main ]

jobs:
  hehehehe:

    runs-on: ubuntu-latest

    steps:
    - name: Test with pytest
      run: |
        for i in 1 2 3 4 5
        do
          seq -f 'user_%03g' ${i} ${i}
          sleep 10 &
        done

